# oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias gut="git"

# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

# Customize to your needs... (use subl to open sublime text and edit)
export EDITOR='subl -w'

# Development stuff
export ENVIRONMENT="development"
alias subl="nocorrect subl"

export PATH=/usr/local/bin:$PATH
PATH=$PATH:$HOME/.rvm/bin:/Users/bradley/bin:/usr/local/sbin # Add RVM to PATH for script

# Custom script for opening xcode projects using xc command
xc(){
  x_proj=`find . -name "*.xc*" -d 1 | sort -r | head -1`
  if [ `echo -n $x_proj | wc -m` '==' 0 ]
  then
    echo "No xcworkspace/xcodeproj file found in the current directory."
    exit 1
  fi

  echo "Found $x_proj"
  open "$x_proj"
}

source /opt/boxen/env.sh
source $ZSH/oh-my-zsh.sh
